# Generated by Django 2.1.3 on 2018-12-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181210_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_publicacao',
            field=models.CharField(default='', max_length=900000000000000, null=True),
        ),
    ]
