# Generated by Django 2.0.4 on 2018-12-13 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_id_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='palavras_chaves',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.ManyToManyField(to='app.Tipo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
